Repository Nest-final-project/Nest.dev, pull requests merged in 2025-06, with the labels that each got.

#11 [#8] feat: 티켓 수정, 삭제 작업 완료 및 BaseException 수정
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/common/enums/SuccessCode.java
  src/main/java/caffeine/nest_dev/common/exception/BaseException.java
  src/main/java/caffeine/nest_dev/domain/ticket/controller/TicketController.java
  src/main/java/caffeine/nest_dev/domain/ticket/entity/Ticket.java
  src/main/java/caffeine/nest_dev/domain/ticket/service/TicketService.java
Labels: feature

#15 Feat/admin : 관리자 멘토 경력 확인 요청 조회,수정
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/common/enums/SuccessCode.java
  src/main/java/caffeine/nest_dev/common/exception/GlobalExceptionHandler.java
  src/main/java/caffeine/nest_dev/domain/admin/controller/AdminController.java
  src/main/java/caffeine/nest_dev/domain/admin/dto/request/AdminRequestDto.java
  src/main/java/caffeine/nest_dev/domain/admin/dto/response/AdminMentorCareerResponseDto.java
  src/main/java/caffeine/nest_dev/domain/admin/dto/response/AdminResponseDto.java
  src/main/java/caffeine/nest_dev/domain/admin/service/AdminService.java
  src/main/java/caffeine/nest_dev/domain/career/entity/Career.java
  src/main/java/caffeine/nest_dev/domain/career/entity/Certificate.java
  src/main/java/caffeine/nest_dev/domain/career/repository/CareerRepository.java
  src/main/java/caffeine/nest_dev/domain/profile/entity/Profile.java
Labels: feature

#19 [#18] fix: 관리자 쿠폰 조회 오류 수정
  src/main/java/caffeine/nest_dev/domain/coupon/controller/AdminCouponController.java
  src/main/java/caffeine/nest_dev/domain/coupon/repository/AdminCouponRepository.java
  src/main/java/caffeine/nest_dev/domain/coupon/service/AdminCouponService.java
Labels: fix

#30 refactor: Controller 삭제 부분 Object 타입 void로 변경 및 ddl-auto create로 변경
  src/main/java/caffeine/nest_dev/domain/coupon/controller/AdminCouponController.java
  src/main/java/caffeine/nest_dev/domain/ticket/controller/TicketController.java
  src/main/resources/application.properties
Labels: refactoring

#35 Feat/admin Fix: dto에 변환메서드 빌더 생성
  src/main/java/caffeine/nest_dev/domain/admin/controller/AdminController.java
  src/main/java/caffeine/nest_dev/domain/category/controller/CategoryController.java
  src/main/java/caffeine/nest_dev/domain/category/dto/request/CategoryRequestDto.java
  src/main/java/caffeine/nest_dev/domain/category/service/CategoryService.java
  src/main/java/caffeine/nest_dev/domain/chatroom/controller/ChatRoomController.java
  src/main/java/caffeine/nest_dev/domain/chatroom/service/ChatRoomService.java
Labels: fix

#37 [#33] Feat/complaint
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/common/enums/SuccessCode.java
  src/main/java/caffeine/nest_dev/domain/complaint/controller/ComplaintController.java
  src/main/java/caffeine/nest_dev/domain/complaint/dto/request/ComplaintRequestDto.java
  src/main/java/caffeine/nest_dev/domain/complaint/dto/response/ComplaintResponseDto.java
  src/main/java/caffeine/nest_dev/domain/complaint/entity/Complaint.java
  src/main/java/caffeine/nest_dev/domain/complaint/enums/ComplaintType.java
  src/main/java/caffeine/nest_dev/domain/complaint/repository/ComplaintRepository.java
  src/main/java/caffeine/nest_dev/domain/complaint/service/ComplaintService.java
  src/main/java/caffeine/nest_dev/domain/reservation/enums/ReservationStatus.java
  src/main/java/caffeine/nest_dev/domain/review/service/ReviewService.java
Labels: feature

#42 [#41] Feat/review refactoring
  src/main/java/caffeine/nest_dev/domain/review/controller/ReviewController.java
  src/main/java/caffeine/nest_dev/domain/review/service/ReviewService.java
Labels: refactoring

#43 [#26] feat: 유저 쿠폰 생성, 조회, 수정 기능 구현
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/common/enums/SuccessCode.java
  src/main/java/caffeine/nest_dev/domain/coupon/controller/UserCouponController.java
  src/main/java/caffeine/nest_dev/domain/coupon/dto/request/UserCouponRequestDto.java
  src/main/java/caffeine/nest_dev/domain/coupon/dto/response/AdminCouponResponseDto.java
  src/main/java/caffeine/nest_dev/domain/coupon/dto/response/UserCouponResponseDto.java
  src/main/java/caffeine/nest_dev/domain/coupon/entity/Coupon.java
  src/main/java/caffeine/nest_dev/domain/coupon/entity/UserCoupon.java
  src/main/java/caffeine/nest_dev/domain/coupon/entity/UserCouponId.java
  src/main/java/caffeine/nest_dev/domain/coupon/repository/UserCouponRepository.java
  src/main/java/caffeine/nest_dev/domain/coupon/service/AdminCouponService.java
  src/main/java/caffeine/nest_dev/domain/coupon/service/UserCouponService.java
Labels: feature

#69 [#68] feat: 상담 시간 도메인 기능
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/common/enums/SuccessCode.java
  src/main/java/caffeine/nest_dev/domain/consultation/controller/ConsultationController.java
  src/main/java/caffeine/nest_dev/domain/consultation/dto/request/ConsultationRequestDto.java
  src/main/java/caffeine/nest_dev/domain/consultation/dto/response/ConsultationResponseDto.java
  src/main/java/caffeine/nest_dev/domain/consultation/entity/Consultation.java
  src/main/java/caffeine/nest_dev/domain/consultation/repository/ConsultationQueryRepository.java
  src/main/java/caffeine/nest_dev/domain/consultation/repository/ConsultationQueryRepositoryImpl.java
  src/main/java/caffeine/nest_dev/domain/consultation/repository/ConsultationRepository.java
  src/main/java/caffeine/nest_dev/domain/consultation/service/ConsultationService.java
  src/main/java/caffeine/nest_dev/domain/keyword/controller/KeywordController.java
  src/main/java/caffeine/nest_dev/domain/profile/service/ProfileService.java
Labels: feature

#76 [#75] Feat/complaint
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/domain/complaint/controller/ComplaintController.java
  src/main/java/caffeine/nest_dev/domain/complaint/repository/ComplaintRepository.java
  src/main/java/caffeine/nest_dev/domain/complaint/service/ComplaintService.java
Labels: fix

#83 [#82] Feat/admin complaint
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/common/enums/SuccessCode.java
  src/main/java/caffeine/nest_dev/domain/complaint/controller/AdminComplaintController.java
  src/main/java/caffeine/nest_dev/domain/complaint/dto/request/AnswerRequestDto.java
  src/main/java/caffeine/nest_dev/domain/complaint/dto/request/AnswerUpdateRequestDto.java
  src/main/java/caffeine/nest_dev/domain/complaint/dto/response/AnswerResponseDto.java
  src/main/java/caffeine/nest_dev/domain/complaint/dto/response/ComplaintResponseDto.java
  src/main/java/caffeine/nest_dev/domain/complaint/entity/Answer.java
  src/main/java/caffeine/nest_dev/domain/complaint/entity/Complaint.java
  src/main/java/caffeine/nest_dev/domain/complaint/repository/AnswerRepository.java
  src/main/java/caffeine/nest_dev/domain/complaint/repository/ComplaintRepository.java
  src/main/java/caffeine/nest_dev/domain/complaint/service/AdminComplaintService.java
Labels: feature

#91 [#90] Feat/reservation v2
  build.gradle
  src/main/java/caffeine/nest_dev/common/exception/GlobalExceptionHandler.java
  src/main/java/caffeine/nest_dev/domain/reservation/controller/ReservationController.java
  src/main/java/caffeine/nest_dev/domain/reservation/dto/request/ReservationCancelRequestDto.java
  src/main/java/caffeine/nest_dev/domain/reservation/dto/request/ReservationRequestDto.java
  src/main/java/caffeine/nest_dev/domain/reservation/entity/Reservation.java
  src/main/java/caffeine/nest_dev/domain/reservation/enums/ReservationStatus.java
  src/main/java/caffeine/nest_dev/domain/reservation/lock/DistributedLock.java
  src/main/java/caffeine/nest_dev/domain/reservation/lock/DistributedLockAspect.java
  src/main/java/caffeine/nest_dev/domain/reservation/lock/RedisConfig.java
  src/main/java/caffeine/nest_dev/domain/reservation/repository/ReservationRepository.java
  src/main/java/caffeine/nest_dev/domain/reservation/service/ReservationService.java
Labels: feature

#98 refactor: TicketResponseDto Payment 삭제
  src/main/java/caffeine/nest_dev/domain/ticket/dto/response/TicketResponseDto.java
Labels: refactoring

#125 [#124]fix: 유저 쿠폰 사용 시 결제 준비 과정에 적용, 할인 전 원가 금액 entity에 저장
  src/main/java/caffeine/nest_dev/domain/payment/controller/PaymentController.java
  src/main/java/caffeine/nest_dev/domain/payment/dto/request/PaymentConfirmRequestDto.java
  src/main/java/caffeine/nest_dev/domain/payment/entity/Payment.java
  src/main/java/caffeine/nest_dev/domain/payment/service/PaymentService.java
  src/main/java/caffeine/nest_dev/domain/reservation/dto/request/ReservationRequestDto.java
Labels: fix

#144 [#143] feat: 최소 주문 금액 및 할인 타입 생성
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/domain/coupon/controller/AdminCouponController.java
  src/main/java/caffeine/nest_dev/domain/coupon/controller/UserCouponController.java
  src/main/java/caffeine/nest_dev/domain/coupon/dto/request/AdminCouponRequestDto.java
  src/main/java/caffeine/nest_dev/domain/coupon/dto/response/AdminCouponResponseDto.java
  src/main/java/caffeine/nest_dev/domain/coupon/entity/Coupon.java
  src/main/java/caffeine/nest_dev/domain/coupon/enums/CouponDiscountType.java
  src/main/java/caffeine/nest_dev/domain/coupon/service/UserCouponService.java
  src/main/java/caffeine/nest_dev/domain/payment/service/PaymentService.java
Labels: feature

#153 [#152] Feat/admin complaint v2
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/common/enums/SuccessCode.java
  src/main/java/caffeine/nest_dev/domain/complaint/controller/AdminComplaintController.java
  src/main/java/caffeine/nest_dev/domain/complaint/controller/ComplaintController.java
  src/main/java/caffeine/nest_dev/domain/complaint/repository/AnswerRepository.java
  src/main/java/caffeine/nest_dev/domain/complaint/service/AdminComplaintService.java
  src/main/java/caffeine/nest_dev/domain/complaint/service/ComplaintService.java
Labels: feature
