Repository Nest-final-project/Nest.dev, pull requests merged in 2025-07, with the labels that each got.

#173 [#172] refactor: 상담 시간 수정부분 삭제
  src/main/java/caffeine/nest_dev/domain/consultation/controller/ConsultationController.java
  src/main/java/caffeine/nest_dev/domain/consultation/service/ConsultationService.java
Labels: refactoring

#175 [#174] refactor: 쿠폰 현재 발급된 수량 0 지정
  src/main/java/caffeine/nest_dev/domain/coupon/entity/Coupon.java
Labels: refactoring

#179 [#178] feat: prometheus, grafana 모니터링 연동 세팅
  build.gradle
  docker-compose.yml
  grafana/provisioning/dashboards/dashboard.yml
  grafana/provisioning/datasources/prometheus.yml
  prometheus.yml
  src/main/java/caffeine/nest_dev/common/config/JwtAuthenticationFilter.java
  src/main/java/caffeine/nest_dev/common/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: feature

#182 Feat : 프로필 삭제, 중복 프로필 생성 금지 추가
  build.gradle
  src/main/java/caffeine/nest_dev/common/config/SecurityConfig.java
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/common/enums/SuccessCode.java
  src/main/java/caffeine/nest_dev/domain/profile/controller/ProfileController.java
  src/main/java/caffeine/nest_dev/domain/profile/entity/Profile.java
  src/main/java/caffeine/nest_dev/domain/profile/repository/ProfileRepository.java
  src/main/java/caffeine/nest_dev/domain/profile/service/ProfileService.java
Labels: fix, feature

#186 [#185] refactor: 쿠폰 동시성 문제 해결
  src/main/java/caffeine/nest_dev/common/enums/ErrorCode.java
  src/main/java/caffeine/nest_dev/domain/coupon/entity/Coupon.java
  src/main/java/caffeine/nest_dev/domain/coupon/service/UserCouponService.java
Labels: refactoring

#213 fix: @Valid 오류 수정
  src/main/java/caffeine/nest_dev/domain/payment/dto/request/PaymentConfirmRequestDto.java
  src/main/java/caffeine/nest_dev/domain/payment/dto/request/PaymentPrepareRequestDto.java
Labels: fix
